# Generated by Django 4.1.4 on 2023-01-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0002_carritos_cliente_productos_delete_familiares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritos',
            name='price',
        ),
    ]
