# Generated by Django 4.1.4 on 2023-01-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0004_alter_carritos_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='description',
            field=models.CharField(default='Sin descripcion', max_length=100),
        ),
        migrations.AddField(
            model_name='productos',
            name='image',
            field=models.CharField(default='No hay descripcion', max_length=200),
            preserve_default=False,
        ),
    ]
