# Generated by Django 4.1.4 on 2023-01-22 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
